drop table if exists `WEATHER_DATA`;
CREATE TABLE `WEATHER_DATA` (
  `ZIPCODE` INT(10) UNSIGNED NOT NULL,
  `CONDITION` VARCHAR(30),
  `LOW_TEMP` FLOAT,
  `HIGH_TEMP`FLOAT,
  PRIMARY KEY (`ZIPCODE`)
);
